### ISSUE TITLE
[FE] 개발자 행사조회 개선 

### ISSUE THREAD

**Issue by ohh31** [brave-people/Dev-Event-Web#38]
8월 13일 - 8월 22일
 
- [x] SEO 개선 #26 
- [x] 새로 업데이트된 행사 필터링 기능 추가 #43
- [x] #47
- [x] 검색 결과 URL를 직접 입력했을 때 데이터가 없는 문제 해결  #23 
- [x] #41 

8월 22일 - 8월 27일 

- [x] 찜 추가 시 일부 이벤트 UI가 업데이트 되지 않는 문제 #34
- [x] 내 이벤트 조회 시 결과가 안 나오는 문제 #35
- [ ] 찜 기능 속도 개선 #36

9월 13일 - 9월 18일 

- [ ] alert를 토스트 모달로 변경 #27
- [ ] 개발자행사 v2 api로 변경  
- [ ] infinite scroll 구현 
- [ ] 찜 기능 속도 개선 #36
